### ISSUE TITLE
How about running this software in GNU/Linux ?

### ISSUE THREAD

**Issue by lopippo** [BlaisProteomics/mzStudio#41]
Greetings,
the subject tells it all...

Thank you,
lopippo

**Comment by MaxAlex** [comment]
There currently aren't any *known* *insurmountable* issues with using mzStudio in Linux.  You're welcome to try it and let us know what happens (mzStudio is still Python2-bound, however.)

You will likely, however, run into problems with the installation of multiplierz, since the pythonnet/mono system used for Thermo file access on Linux is still highly unstable (the instability isn't on our end.)  If you are reasonably comfortable with Docker, multiplierz-on-Linux can be [reproducibly built using this Dockerfile](https://gist.github.com/MaxAlex/d976babed8e2e92db962e5319791d2a4), and you can try getting mzStudio running on top of that.  

A tutorial/Dockerfile/image for how to get a mzStudio-on-Docker "out of the box" is on our to-do list (once I myself understand Docker a bit better.)

**Comment by lopippo** [comment]
Thank you for your reply.  On my Debian box, python2 is no more available. 
Sincerely,
lopippo
